// Generated by CoffeeScript 1.6.3
var app, express, http, rwenzServer,
  _this = this;

express = require('express');

app = express();

http = require('http');

rwenzServer = http.createServer(app);

app.configure(function() {
  app.set('views', __dirname + '/../../app');
  app.engine('html', require('ejs').renderFile);
  app.use(express.compress());
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(express["static"](__dirname + '/../../app'));
  return app.use(app.router);
});

app.configure('development', function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

app.configure('production', function() {
  return app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
});

require('./routes/view-routes')(app);

rwenzServer.listen(9949, function() {
  return console.log("Rwenzori server now running -- Server listening on port %d in mode %s", rwenzServer.address().port, app.settings.env);
});
